//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebViewWidget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebViewWidget.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Footer_Ready {
            get {
                return ResourceManager.GetString("Footer.Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Exit.
        /// </summary>
        public static string Menu_Exits {
            get {
                return ResourceManager.GetString("Menu.Exits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😌 Hide All Widgets.
        /// </summary>
        public static string Menu_HideAllWidgets {
            get {
                return ResourceManager.GetString("Menu.HideAllWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👀 Show All Widgets.
        /// </summary>
        public static string Menu_ShowAllWidgets {
            get {
                return ResourceManager.GetString("Menu.ShowAllWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Nav_Portfolio {
            get {
                return ResourceManager.GetString("Nav.Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stock Portfolio.
        /// </summary>
        public static string Portfolio_my_stock_portfolio {
            get {
                return ResourceManager.GetString("Portfolio.my_stock_portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Features.
        /// </summary>
        public static string Premium_Header {
            get {
                return ResourceManager.GetString("Premium.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Widget.
        /// </summary>
        public static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Settings_Apply {
            get {
                return ResourceManager.GetString("Settings.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Widget.
        /// </summary>
        public static string Tray_Header {
            get {
                return ResourceManager.GetString("Tray.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still running here. Double-click to reopen..
        /// </summary>
        public static string Tray_ReopenHint {
            get {
                return ResourceManager.GetString("Tray.ReopenHint", resourceCulture);
            }
        }
    }
}
