//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebViewWidget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebViewWidget.Properties.Strings - Copy", typeof(Strings___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Footer_Ready {
            get {
                return ResourceManager.GetString("Footer.Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exits {
            get {
                return ResourceManager.GetString("Menu.Exits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide All Widgets.
        /// </summary>
        public static string Menu_HideAllWidgets {
            get {
                return ResourceManager.GetString("Menu.HideAllWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dashboard.
        /// </summary>
        public static string Menu_OpenDashboard {
            get {
                return ResourceManager.GetString("Menu.OpenDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Widgets.
        /// </summary>
        public static string Menu_ShowAllWidgets {
            get {
                return ResourceManager.GetString("Menu.ShowAllWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Nav_Portfolio {
            get {
                return ResourceManager.GetString("Nav.Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stock Portfolio.
        /// </summary>
        public static string Portfolio_my_stock_portfolio {
            get {
                return ResourceManager.GetString("Portfolio.my_stock_portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Features.
        /// </summary>
        public static string Premium_Header {
            get {
                return ResourceManager.GetString("Premium.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Widget.
        /// </summary>
        public static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Settings_Apply {
            get {
                return ResourceManager.GetString("Settings.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Minutes.
        /// </summary>
        public static string TimeInterval__15Minutes {
            get {
                return ResourceManager.GetString("TimeInterval__15Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day.
        /// </summary>
        public static string TimeInterval__1Day {
            get {
                return ResourceManager.GetString("TimeInterval__1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hour.
        /// </summary>
        public static string TimeInterval__1Hour {
            get {
                return ResourceManager.GetString("TimeInterval__1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Minute.
        /// </summary>
        public static string TimeInterval__1Minute {
            get {
                return ResourceManager.GetString("TimeInterval__1Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month.
        /// </summary>
        public static string TimeInterval__1Month {
            get {
                return ResourceManager.GetString("TimeInterval__1Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Week.
        /// </summary>
        public static string TimeInterval__1Week {
            get {
                return ResourceManager.GetString("TimeInterval__1Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Minutes.
        /// </summary>
        public static string TimeInterval__2Minutes {
            get {
                return ResourceManager.GetString("TimeInterval__2Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Minutes.
        /// </summary>
        public static string TimeInterval__30Minutes {
            get {
                return ResourceManager.GetString("TimeInterval__30Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Months.
        /// </summary>
        public static string TimeInterval__3Months {
            get {
                return ResourceManager.GetString("TimeInterval__3Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Days.
        /// </summary>
        public static string TimeInterval__5Days {
            get {
                return ResourceManager.GetString("TimeInterval__5Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Minutes.
        /// </summary>
        public static string TimeInterval__5Minutes {
            get {
                return ResourceManager.GetString("TimeInterval__5Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 Minutes.
        /// </summary>
        public static string TimeInterval__60Minutes {
            get {
                return ResourceManager.GetString("TimeInterval__60Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 Minutes.
        /// </summary>
        public static string TimeInterval__90Minutes {
            get {
                return ResourceManager.GetString("TimeInterval__90Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Years.
        /// </summary>
        public static string TimeRange__10Years {
            get {
                return ResourceManager.GetString("TimeRange__10Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day.
        /// </summary>
        public static string TimeRange__1Day {
            get {
                return ResourceManager.GetString("TimeRange__1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month.
        /// </summary>
        public static string TimeRange__1Month {
            get {
                return ResourceManager.GetString("TimeRange__1Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Year.
        /// </summary>
        public static string TimeRange__1Year {
            get {
                return ResourceManager.GetString("TimeRange__1Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Years.
        /// </summary>
        public static string TimeRange__2Years {
            get {
                return ResourceManager.GetString("TimeRange__2Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Months.
        /// </summary>
        public static string TimeRange__3Months {
            get {
                return ResourceManager.GetString("TimeRange__3Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Days.
        /// </summary>
        public static string TimeRange__5Days {
            get {
                return ResourceManager.GetString("TimeRange__5Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Years.
        /// </summary>
        public static string TimeRange__5Years {
            get {
                return ResourceManager.GetString("TimeRange__5Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Months.
        /// </summary>
        public static string TimeRange__6Months {
            get {
                return ResourceManager.GetString("TimeRange__6Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string TimeRange__Max {
            get {
                return ResourceManager.GetString("TimeRange__Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year to Date.
        /// </summary>
        public static string TimeRange__YearToDate {
            get {
                return ResourceManager.GetString("TimeRange__YearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added to your Desktop..
        /// </summary>
        public static string Toast_AddedStock {
            get {
                return ResourceManager.GetString("Toast.AddedStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in your portfolio..
        /// </summary>
        public static string Toast_AlreadyInPortfolio {
            get {
                return ResourceManager.GetString("Toast.AlreadyInPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Removed..
        /// </summary>
        public static string Toast_StockRemoved {
            get {
                return ResourceManager.GetString("Toast.StockRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Widget.
        /// </summary>
        public static string Tray_Header {
            get {
                return ResourceManager.GetString("Tray.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still running here. Double-click to reopen..
        /// </summary>
        public static string Tray_ReopenHint {
            get {
                return ResourceManager.GetString("Tray.ReopenHint", resourceCulture);
            }
        }
    }
}
